/**:
  ros__parameters:
    # RBY1 initialize Information
    robot_ip: "127.0.0.1:50051"
    model: "m" # A or M , a or m


    # drive parameters
    get_state_period: 0.01 # seconds
    minimum_time: 2.0 # seconds
    stream_hz: 30.0

    angular_velocity_limit: 4.712388 # 3.141592 * 1.5
    linear_velocity_limit: 1.5
    acceleration_limit: 1.0
    stop_orientation_tracking_error: 1e-5
    stop_position_tracking_error: 1e-5

    # SE2/Mobile base parameters for smooth streaming control
    se2_minimum_time: 1.0 # seconds
    se2_linear_acceleration_limit: 0.5
    se2_angular_acceleration_limit: 0.5


    # additional options
    fault_reset_trigger: false 
    
    # Collision options
    collision_threshold: 0.02 # meter

    # Status publish triggers
    publish_battery_state: true
    publish_tool_flange_state: true
     
